/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sbi.wms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Exclusif_WMS service. Represents a row in the &quot;SBI_Exclusif_WMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbi.wms.model.impl.Exclusif_WMSModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbi.wms.model.impl.Exclusif_WMSImpl}.
 * </p>
 *
 * @author Syed
 * @see Exclusif_WMS
 * @see com.sbi.wms.model.impl.Exclusif_WMSImpl
 * @see com.sbi.wms.model.impl.Exclusif_WMSModelImpl
 * @generated
 */
public interface Exclusif_WMSModel extends BaseModel<Exclusif_WMS> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exclusif_ w m s model instance should use the {@link Exclusif_WMS} interface instead.
	 */

	/**
	 * Returns the primary key of this exclusif_ w m s.
	 *
	 * @return the primary key of this exclusif_ w m s
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exclusif_ w m s.
	 *
	 * @param primaryKey the primary key of this exclusif_ w m s
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this exclusif_ w m s.
	 *
	 * @return the rec ID of this exclusif_ w m s
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this exclusif_ w m s.
	 *
	 * @param recId the rec ID of this exclusif_ w m s
	 */
	public void setRecId(long recId);

	/**
	 * Returns the name of this exclusif_ w m s.
	 *
	 * @return the name of this exclusif_ w m s
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this exclusif_ w m s.
	 *
	 * @param name the name of this exclusif_ w m s
	 */
	public void setName(String name);

	/**
	 * Returns the city of this exclusif_ w m s.
	 *
	 * @return the city of this exclusif_ w m s
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this exclusif_ w m s.
	 *
	 * @param city the city of this exclusif_ w m s
	 */
	public void setCity(String city);

	/**
	 * Returns the mobileno of this exclusif_ w m s.
	 *
	 * @return the mobileno of this exclusif_ w m s
	 */
	public long getMobileno();

	/**
	 * Sets the mobileno of this exclusif_ w m s.
	 *
	 * @param mobileno the mobileno of this exclusif_ w m s
	 */
	public void setMobileno(long mobileno);

	/**
	 * Returns the email of this exclusif_ w m s.
	 *
	 * @return the email of this exclusif_ w m s
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this exclusif_ w m s.
	 *
	 * @param email the email of this exclusif_ w m s
	 */
	public void setEmail(String email);

	/**
	 * Returns the agree of this exclusif_ w m s.
	 *
	 * @return the agree of this exclusif_ w m s
	 */
	@AutoEscape
	public String getAgree();

	/**
	 * Sets the agree of this exclusif_ w m s.
	 *
	 * @param agree the agree of this exclusif_ w m s
	 */
	public void setAgree(String agree);

	/**
	 * Returns the company ID of this exclusif_ w m s.
	 *
	 * @return the company ID of this exclusif_ w m s
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this exclusif_ w m s.
	 *
	 * @param companyId the company ID of this exclusif_ w m s
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this exclusif_ w m s.
	 *
	 * @return the group ID of this exclusif_ w m s
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this exclusif_ w m s.
	 *
	 * @param groupId the group ID of this exclusif_ w m s
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this exclusif_ w m s.
	 *
	 * @return the user ID of this exclusif_ w m s
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this exclusif_ w m s.
	 *
	 * @param userId the user ID of this exclusif_ w m s
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this exclusif_ w m s.
	 *
	 * @return the user uuid of this exclusif_ w m s
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this exclusif_ w m s.
	 *
	 * @param userUuid the user uuid of this exclusif_ w m s
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this exclusif_ w m s.
	 *
	 * @return the create date of this exclusif_ w m s
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this exclusif_ w m s.
	 *
	 * @param createDate the create date of this exclusif_ w m s
	 */
	public void setCreateDate(Date createDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Exclusif_WMS exclusif_WMS);

	public int hashCode();

	public CacheModel<Exclusif_WMS> toCacheModel();

	public Exclusif_WMS toEscapedModel();

	public Exclusif_WMS toUnescapedModel();

	public String toString();

	public String toXmlString();
}