/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sbi.wms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WMS_INB_BRANCH_MASTER service. Represents a row in the &quot;SBI_WMS_INB_BRANCH_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbi.wms.model.impl.WMS_INB_BRANCH_MASTERModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbi.wms.model.impl.WMS_INB_BRANCH_MASTERImpl}.
 * </p>
 *
 * @author Syed
 * @see WMS_INB_BRANCH_MASTER
 * @see com.sbi.wms.model.impl.WMS_INB_BRANCH_MASTERImpl
 * @see com.sbi.wms.model.impl.WMS_INB_BRANCH_MASTERModelImpl
 * @generated
 */
public interface WMS_INB_BRANCH_MASTERModel extends BaseModel<WMS_INB_BRANCH_MASTER> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w m s_ i n b_ b r a n c h_ m a s t e r model instance should use the {@link WMS_INB_BRANCH_MASTER} interface instead.
	 */

	/**
	 * Returns the primary key of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the primary key of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param primaryKey the primary key of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the r e c_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the r e c_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public long getREC_ID();

	/**
	 * Sets the r e c_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param REC_ID the r e c_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setREC_ID(long REC_ID);

	/**
	 * Returns the b r a n c h_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the b r a n c h_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getBRANCH_CODE();

	/**
	 * Sets the b r a n c h_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param BRANCH_CODE the b r a n c h_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setBRANCH_CODE(String BRANCH_CODE);

	/**
	 * Returns the b r a n c h_ n a m e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the b r a n c h_ n a m e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getBRANCH_NAME();

	/**
	 * Sets the b r a n c h_ n a m e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param BRANCH_NAME the b r a n c h_ n a m e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setBRANCH_NAME(String BRANCH_NAME);

	/**
	 * Returns the m a i l_ a d d r e s s1 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the m a i l_ a d d r e s s1 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getMAIL_ADDRESS1();

	/**
	 * Sets the m a i l_ a d d r e s s1 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param MAIL_ADDRESS1 the m a i l_ a d d r e s s1 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setMAIL_ADDRESS1(String MAIL_ADDRESS1);

	/**
	 * Returns the m a i l_ a d d r e s s2 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the m a i l_ a d d r e s s2 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getMAIL_ADDRESS2();

	/**
	 * Sets the m a i l_ a d d r e s s2 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param MAIL_ADDRESS2 the m a i l_ a d d r e s s2 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setMAIL_ADDRESS2(String MAIL_ADDRESS2);

	/**
	 * Returns the m a i l_ a d d r e s s3 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the m a i l_ a d d r e s s3 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getMAIL_ADDRESS3();

	/**
	 * Sets the m a i l_ a d d r e s s3 of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param MAIL_ADDRESS3 the m a i l_ a d d r e s s3 of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setMAIL_ADDRESS3(String MAIL_ADDRESS3);

	/**
	 * Returns the c i t y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the c i t y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getCITY();

	/**
	 * Sets the c i t y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param CITY the c i t y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setCITY(String CITY);

	/**
	 * Returns the d i s t r i c t of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the d i s t r i c t of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getDISTRICT();

	/**
	 * Sets the d i s t r i c t of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param DISTRICT the d i s t r i c t of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setDISTRICT(String DISTRICT);

	/**
	 * Returns the s t a t e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s t a t e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSTATE();

	/**
	 * Sets the s t a t e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param STATE the s t a t e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSTATE(String STATE);

	/**
	 * Returns the p i n of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the p i n of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getPIN();

	/**
	 * Sets the p i n of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param PIN the p i n of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setPIN(String PIN);

	/**
	 * Returns the c i r c l e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the c i r c l e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getCIRCLE();

	/**
	 * Sets the c i r c l e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param CIRCLE the c i r c l e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setCIRCLE(String CIRCLE);

	/**
	 * Returns the f o r e x_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the f o r e x_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getFOREX_TYPE();

	/**
	 * Sets the f o r e x_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param FOREX_TYPE the f o r e x_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setFOREX_TYPE(String FOREX_TYPE);

	/**
	 * Returns the b r a n c h_ m a n a g e r of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the b r a n c h_ m a n a g e r of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getBRANCH_MANAGER();

	/**
	 * Sets the b r a n c h_ m a n a g e r of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param BRANCH_MANAGER the b r a n c h_ m a n a g e r of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setBRANCH_MANAGER(String BRANCH_MANAGER);

	/**
	 * Returns the n o_ o f_ a t m of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the n o_ o f_ a t m of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getNO_OF_ATM();

	/**
	 * Sets the n o_ o f_ a t m of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param NO_OF_ATM the n o_ o f_ a t m of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setNO_OF_ATM(String NO_OF_ATM);

	/**
	 * Returns the i f s c_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the i f s c_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getIFSC_CODE();

	/**
	 * Sets the i f s c_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param IFSC_CODE the i f s c_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setIFSC_CODE(String IFSC_CODE);

	/**
	 * Returns the s t d_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s t d_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSTD_CODE();

	/**
	 * Sets the s t d_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param STD_CODE the s t d_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSTD_CODE(String STD_CODE);

	/**
	 * Returns the t e l e p h o n e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the t e l e p h o n e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getTELEPHONE();

	/**
	 * Sets the t e l e p h o n e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param TELEPHONE the t e l e p h o n e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setTELEPHONE(String TELEPHONE);

	/**
	 * Returns the f a x_ n o of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the f a x_ n o of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getFAX_NO();

	/**
	 * Sets the f a x_ n o of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param FAX_NO the f a x_ n o of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setFAX_NO(String FAX_NO);

	/**
	 * Returns the e m a i l_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the e m a i l_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getEMAIL_ID();

	/**
	 * Sets the e m a i l_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param EMAIL_ID the e m a i l_ i d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setEMAIL_ID(String EMAIL_ID);

	/**
	 * Returns the b u s s i n e s s_ h o u r s of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the b u s s i n e s s_ h o u r s of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getBUSSINESS_HOURS();

	/**
	 * Sets the b u s s i n e s s_ h o u r s of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param BUSSINESS_HOURS the b u s s i n e s s_ h o u r s of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setBUSSINESS_HOURS(String BUSSINESS_HOURS);

	/**
	 * Returns the w e e k l y_ h o l i d a y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the w e e k l y_ h o l i d a y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getWEEKLY_HOLIDAY();

	/**
	 * Sets the w e e k l y_ h o l i d a y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param WEEKLY_HOLIDAY the w e e k l y_ h o l i d a y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setWEEKLY_HOLIDAY(String WEEKLY_HOLIDAY);

	/**
	 * Returns the n o n_ b a n k i n g_ d a y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the n o n_ b a n k i n g_ d a y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getNON_BANKING_DAY();

	/**
	 * Sets the n o n_ b a n k i n g_ d a y of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param NON_BANKING_DAY the n o n_ b a n k i n g_ d a y of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setNON_BANKING_DAY(String NON_BANKING_DAY);

	/**
	 * Returns the s u n d a y_ b a n k i n g of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s u n d a y_ b a n k i n g of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSUNDAY_BANKING();

	/**
	 * Sets the s u n d a y_ b a n k i n g of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param SUNDAY_BANKING the s u n d a y_ b a n k i n g of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSUNDAY_BANKING(String SUNDAY_BANKING);

	/**
	 * Returns the s u n d a y_ b a n k i n g_ b u s s i n e s s of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s u n d a y_ b a n k i n g_ b u s s i n e s s of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSUNDAY_BANKING_BUSSINESS();

	/**
	 * Sets the s u n d a y_ b a n k i n g_ b u s s i n e s s of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param SUNDAY_BANKING_BUSSINESS the s u n d a y_ b a n k i n g_ b u s s i n e s s of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSUNDAY_BANKING_BUSSINESS(String SUNDAY_BANKING_BUSSINESS);

	/**
	 * Returns the s w i f t_ e n a b l e d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s w i f t_ e n a b l e d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSWIFT_ENABLED();

	/**
	 * Sets the s w i f t_ e n a b l e d of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param SWIFT_ENABLED the s w i f t_ e n a b l e d of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSWIFT_ENABLED(String SWIFT_ENABLED);

	/**
	 * Returns the s w i f t_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the s w i f t_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getSWIFT_CODE();

	/**
	 * Sets the s w i f t_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param SWIFT_CODE the s w i f t_ c o d e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setSWIFT_CODE(String SWIFT_CODE);

	/**
	 * Returns the b r a n c h_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the b r a n c h_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getBRANCH_TYPE();

	/**
	 * Sets the b r a n c h_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param BRANCH_TYPE the b r a n c h_ t y p e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setBRANCH_TYPE(String BRANCH_TYPE);

	/**
	 * Returns the l o c k e r of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the l o c k e r of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getLOCKER();

	/**
	 * Sets the l o c k e r of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param LOCKER the l o c k e r of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setLOCKER(String LOCKER);

	/**
	 * Returns the g o l d_ c o i n of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the g o l d_ c o i n of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	@AutoEscape
	public String getGOLD_COIN();

	/**
	 * Sets the g o l d_ c o i n of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param GOLD_COIN the g o l d_ c o i n of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setGOLD_COIN(String GOLD_COIN);

	/**
	 * Returns the l a s t_ m o d_ t i m e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @return the l a s t_ m o d_ t i m e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public Date getLAST_MOD_TIME();

	/**
	 * Sets the l a s t_ m o d_ t i m e of this w m s_ i n b_ b r a n c h_ m a s t e r.
	 *
	 * @param LAST_MOD_TIME the l a s t_ m o d_ t i m e of this w m s_ i n b_ b r a n c h_ m a s t e r
	 */
	public void setLAST_MOD_TIME(Date LAST_MOD_TIME);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WMS_INB_BRANCH_MASTER wms_inb_branch_master);

	public int hashCode();

	public CacheModel<WMS_INB_BRANCH_MASTER> toCacheModel();

	public WMS_INB_BRANCH_MASTER toEscapedModel();

	public WMS_INB_BRANCH_MASTER toUnescapedModel();

	public String toString();

	public String toXmlString();
}