/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sbi.wms.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.sbi.wms.model.WMS_INB_BRANCH_MASTER;
import com.sbi.wms.service.Exclusif_WMSLocalService;
import com.sbi.wms.service.Exclusif_WMSService;
import com.sbi.wms.service.WMS_INB_BRANCH_MASTERLocalService;
import com.sbi.wms.service.WMS_INB_BRANCH_MASTERService;
import com.sbi.wms.service.persistence.Exclusif_WMSPersistence;
import com.sbi.wms.service.persistence.WMS_INB_BRANCH_MASTERPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the w m s_ i n b_ b r a n c h_ m a s t e r remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.sbi.wms.service.impl.WMS_INB_BRANCH_MASTERServiceImpl}.
 * </p>
 *
 * @author Syed
 * @see com.sbi.wms.service.impl.WMS_INB_BRANCH_MASTERServiceImpl
 * @see com.sbi.wms.service.WMS_INB_BRANCH_MASTERServiceUtil
 * @generated
 */
public abstract class WMS_INB_BRANCH_MASTERServiceBaseImpl
	extends BaseServiceImpl implements WMS_INB_BRANCH_MASTERService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.sbi.wms.service.WMS_INB_BRANCH_MASTERServiceUtil} to access the w m s_ i n b_ b r a n c h_ m a s t e r remote service.
	 */

	/**
	 * Returns the exclusif_ w m s local service.
	 *
	 * @return the exclusif_ w m s local service
	 */
	public Exclusif_WMSLocalService getExclusif_WMSLocalService() {
		return exclusif_WMSLocalService;
	}

	/**
	 * Sets the exclusif_ w m s local service.
	 *
	 * @param exclusif_WMSLocalService the exclusif_ w m s local service
	 */
	public void setExclusif_WMSLocalService(
		Exclusif_WMSLocalService exclusif_WMSLocalService) {
		this.exclusif_WMSLocalService = exclusif_WMSLocalService;
	}

	/**
	 * Returns the exclusif_ w m s remote service.
	 *
	 * @return the exclusif_ w m s remote service
	 */
	public Exclusif_WMSService getExclusif_WMSService() {
		return exclusif_WMSService;
	}

	/**
	 * Sets the exclusif_ w m s remote service.
	 *
	 * @param exclusif_WMSService the exclusif_ w m s remote service
	 */
	public void setExclusif_WMSService(Exclusif_WMSService exclusif_WMSService) {
		this.exclusif_WMSService = exclusif_WMSService;
	}

	/**
	 * Returns the exclusif_ w m s persistence.
	 *
	 * @return the exclusif_ w m s persistence
	 */
	public Exclusif_WMSPersistence getExclusif_WMSPersistence() {
		return exclusif_WMSPersistence;
	}

	/**
	 * Sets the exclusif_ w m s persistence.
	 *
	 * @param exclusif_WMSPersistence the exclusif_ w m s persistence
	 */
	public void setExclusif_WMSPersistence(
		Exclusif_WMSPersistence exclusif_WMSPersistence) {
		this.exclusif_WMSPersistence = exclusif_WMSPersistence;
	}

	/**
	 * Returns the w m s_ i n b_ b r a n c h_ m a s t e r local service.
	 *
	 * @return the w m s_ i n b_ b r a n c h_ m a s t e r local service
	 */
	public WMS_INB_BRANCH_MASTERLocalService getWMS_INB_BRANCH_MASTERLocalService() {
		return wms_inb_branch_masterLocalService;
	}

	/**
	 * Sets the w m s_ i n b_ b r a n c h_ m a s t e r local service.
	 *
	 * @param wms_inb_branch_masterLocalService the w m s_ i n b_ b r a n c h_ m a s t e r local service
	 */
	public void setWMS_INB_BRANCH_MASTERLocalService(
		WMS_INB_BRANCH_MASTERLocalService wms_inb_branch_masterLocalService) {
		this.wms_inb_branch_masterLocalService = wms_inb_branch_masterLocalService;
	}

	/**
	 * Returns the w m s_ i n b_ b r a n c h_ m a s t e r remote service.
	 *
	 * @return the w m s_ i n b_ b r a n c h_ m a s t e r remote service
	 */
	public WMS_INB_BRANCH_MASTERService getWMS_INB_BRANCH_MASTERService() {
		return wms_inb_branch_masterService;
	}

	/**
	 * Sets the w m s_ i n b_ b r a n c h_ m a s t e r remote service.
	 *
	 * @param wms_inb_branch_masterService the w m s_ i n b_ b r a n c h_ m a s t e r remote service
	 */
	public void setWMS_INB_BRANCH_MASTERService(
		WMS_INB_BRANCH_MASTERService wms_inb_branch_masterService) {
		this.wms_inb_branch_masterService = wms_inb_branch_masterService;
	}

	/**
	 * Returns the w m s_ i n b_ b r a n c h_ m a s t e r persistence.
	 *
	 * @return the w m s_ i n b_ b r a n c h_ m a s t e r persistence
	 */
	public WMS_INB_BRANCH_MASTERPersistence getWMS_INB_BRANCH_MASTERPersistence() {
		return wms_inb_branch_masterPersistence;
	}

	/**
	 * Sets the w m s_ i n b_ b r a n c h_ m a s t e r persistence.
	 *
	 * @param wms_inb_branch_masterPersistence the w m s_ i n b_ b r a n c h_ m a s t e r persistence
	 */
	public void setWMS_INB_BRANCH_MASTERPersistence(
		WMS_INB_BRANCH_MASTERPersistence wms_inb_branch_masterPersistence) {
		this.wms_inb_branch_masterPersistence = wms_inb_branch_masterPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return WMS_INB_BRANCH_MASTER.class;
	}

	protected String getModelClassName() {
		return WMS_INB_BRANCH_MASTER.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = wms_inb_branch_masterPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = Exclusif_WMSLocalService.class)
	protected Exclusif_WMSLocalService exclusif_WMSLocalService;
	@BeanReference(type = Exclusif_WMSService.class)
	protected Exclusif_WMSService exclusif_WMSService;
	@BeanReference(type = Exclusif_WMSPersistence.class)
	protected Exclusif_WMSPersistence exclusif_WMSPersistence;
	@BeanReference(type = WMS_INB_BRANCH_MASTERLocalService.class)
	protected WMS_INB_BRANCH_MASTERLocalService wms_inb_branch_masterLocalService;
	@BeanReference(type = WMS_INB_BRANCH_MASTERService.class)
	protected WMS_INB_BRANCH_MASTERService wms_inb_branch_masterService;
	@BeanReference(type = WMS_INB_BRANCH_MASTERPersistence.class)
	protected WMS_INB_BRANCH_MASTERPersistence wms_inb_branch_masterPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private WMS_INB_BRANCH_MASTERServiceClpInvoker _clpInvoker = new WMS_INB_BRANCH_MASTERServiceClpInvoker();
}